services:
   postgres:
     image: postgres:15-alpine
     environment:
       POSTGRES_DB: my-finances_dev
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
     ports:
       - 5432:5432

   backend:
     build:
       context: ./backend
       dockerfile: Dockerfile
     ports:
       - 3000:3000
     volumes:
       - ./backend:/usr/src/app
       - /usr/src/app/node_modules
     command: npm run start:migrate:dev
     depends_on:
       - postgres
     environment:
       DATABASE_URL: postgres://postgres@postgres:5432/my-finances_dev
       PORT: 3000

   front:
     build:
       context: ./frontend
       dockerfile: Dockerfile
     ports:
       - 4200:4200
     volumes:
       - ./frontend:/usr/src/front
       - /usr/src/front/node_modules
     command: npm run start -- --host 0.0.0.0
     depends_on:
       - backend
