services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: my-finances_dev
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 9229:9229 # for debugging
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres:5432/my-finances_dev
      PORT: 5000

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start -- --host 0.0.0.0
    depends_on:
      - backend
