services:
  postegres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: my-finances_dev
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  api:
    build: .
    ports:
      - 5000:5000
      - 9229:9229 # for debugging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - postegres
    environment:
      DATABASE_URL: postgres://postgres@postegres:5432/my-finances_dev
      PORT: 5000
